image: comp1531/automarking:latest

stages:
  - lint
  - verify

before_script:
  - npm ci

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: verify
  needs: ["lint"]
  script:
    - npm run build

test:
  stage: verify
  needs: ["lint"]
  script:
    - SERVER_LOG=$(mktemp)
    - npm run start >& "$SERVER_LOG" &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f "$SERVER_LOG") || (cat "$SERVER_LOG" && exit 1)
    - timeout -s SIGINT 180s npm run test || (cat "$SERVER_LOG" && exit 1)
    - kill -SIGINT %1
    - pkill -f node_modules/sync-rpc/lib/worker.js || true
    - sleep 2
    - cat "$SERVER_LOG"
